package client.app;

public enum UiEventType {
	
	START,
	STOP,
	ESEGUI_AZIONE,
	
	// Eventi per richieste di input
    RICHIEDI_INPUT,
    RICHIEDI_CREDENZIALI,
    RICHIEDI_SI_NO,
    RICHIEDI_DATA_VALIDA,
    RICHIEDI_INT,
    RICHIEDI_ORA_VALIDA,
    RICHIEDI_NUMERO_CON_LIMITE,
    RICHIEDI_LUOGO,
    RICHIEDI_TIPO_VISITA,
    RICHIEDI_VOLONTARI,
    RICHIEDI_GIORNI_PRENOTABILI,
    
    // Eventi per visualizzazioni
    VIEW_MESSAGE,
    VIEW_LIST_LUOGO_DTO,
    VIEW_LIST_VISITA_DTO,
    VIEW_LIST_TIPO_VISITA_DTO,
    VIEW_LIST_USER_DTO,
    VIEW_LIST_PRENOTAZIONE_DTO,
    VIEW_LIST_DATA_DISPONIBILITA_DTO,
    
    // Eventi di risposta
    INPUT_RESPONSE,
    CONFIRMATION_RESPONSE
    
}
